version: "3.8"


services:
 postgres:
   image: postgres:15
   container_name: weather-postgres
   environment:
     POSTGRES_USER: etl_user
     POSTGRES_PASSWORD: pass
     POSTGRES_DB: weather_db
   ports:
     - 5432:5432
   volumes:
     - /workspaces/codespaces-blank/weather-etl-project:/app
     - /workspaces/codespaces-blank/weather-etl-project/sql:/docker-entrypoint-initdb.d
     - postgres_data:/var/lib/postgresql/data


volumes:
 postgres_data: